### ISSUE TITLE
Heartbeats Spamming

### ISSUE THREAD

**Issue by eai04191** [vladfaust/unity-wakatime#22]
I am on using Unity 2019.1.2f1. This plugin sends many requests.

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/3516343/67525435-b3754580-f6ed-11e9-9e7e-ad44536bad33.png)

![2019-10-25_06-11-13](https://user-images.githubusercontent.com/3516343/67525835-7c536400-f6ee-11e9-9a73-f76a554268a6.gif)

</details>

Also, when spamming, the API returns `429 Too Many Requests`, so JSON parsing may fail.

```
ArgumentException: JSON parse error: Invalid value.
UnityEngine.JsonUtility.FromJson (System.String json, System.Type type) (at C:/buildslave/unity/build/Modules/JSONSerialize/Public/JsonUtility.bindings.cs:42)
UnityEngine.JsonUtility.FromJson[T] (System.String json) (at C:/buildslave/unity/build/Modules/JSONSerialize/Public/JsonUtility.bindings.cs:30)
WakaTime.Plugin+<>c__DisplayClass21_0.<SendHeartbeat>b__0 (UnityEngine.AsyncOperation operation) (at Library/PackageCache/com.vladfaust.unitywakatime@b8a1d9f726608a3517fade7d045c7c629a57c302/Editor/Plugin.cs:157)
UnityEngine.AsyncOperation.InvokeCompletionEvent () (at C:/buildslave/unity/build/Runtime/Export/Scripting/AsyncOperation.cs:21)
```

**Comment by vladfaust** [comment]
Hello, @eai04191,

I'm on 2020.1.2f1 on Windows, and see no spamming. Could you please share your environment and the program you use to track the requests?

**Comment by vladfaust** [comment]
Shall be related to #23, which is now resolved. Feel free to reopen the issue!
