### ISSUE TITLE
Are you still there??

### ISSUE THREAD

**Issue by Rabadash8820** [vladfaust/unity-wakatime#25]
@vladfaust Your handling of this repository has been pretty infuriating. You haven't made any commits to this repo nor responded to any issues for at least 13 months, despite 4 open issues from the community since 2018, and 4 open Pull Requests since 2019, including one from me. Is it really too much to ask for you to glance at this repo and merge a PR to remove some compiler warnings? You've actually built a pretty handy Wakatime integration here, what with the Unity Package Manager support and removal of Python as a dependency. But good lord, the constant Console warnings from this package when reimporting assets in Unity, mixed with the bugs reported by others, mixed with your laughable project maintenance, has completely soured my taste for this tool, and I have uninstalled it from all of my Unity projects. For a maintainer of multiple other high-starred repos, and for someone with a link to their _Patreon_ account in the README, I would have expected better.

**Comment by vladfaust** [comment]
I hope now you installed it to all of your Unity projects back!
