### ISSUE TITLE
Disable logs

### ISSUE THREAD

**Issue by LeeGrobler** [vladfaust/unity-wakatime#30]
Hi.

How do I disable the constant heartbeat logging? It gets in the way of my actual development.

![logs](https://user-images.githubusercontent.com/16707168/126203346-35539b70-6af9-4432-b5ef-31f63a09fef1.JPG)

Thanks

**Comment by alanhamlett** [comment]
@vladfaust we could change the plugin to only log `Sending heartbeat...` when `debug = true` in the `~/.wakatime.cfg` file?

**Comment by vladfaust** [comment]
@alanhamlett can not reproduce. If I have "debug" unchecked, there are no logs in the console; I've got Unity 2020. Gonna check in 2021 soon

**Comment by LeeGrobler** [comment]
@vladfaust where can I uncheck debug? I want it to stop logging all the heartbeats to my console.

**Comment by alanhamlett** [comment]
Using the menu from this screenshot:
https://github.com/vladfaust/unity-wakatime#unity-wakatime

**Comment by LeeGrobler** [comment]
Ey-ooooh! Not sure how I missed that, but that seems to mostly solve it. It's still dropping this one everyone every time I press play, but aside from that, it's much better. Thank you!

```
A Native Collection has not been disposed, resulting in a memory leak. Enable Full StackTraces to get more details.
```

**Comment by vladfaust** [comment]
Closing this one. @SeriousLee13 see #29.
