### ISSUE TITLE
Broken on Linux. Network is unreachable.

### ISSUE THREAD

**Issue by MyIsaak** [vladfaust/unity-wakatime#8]
My unity editor 2018.2.16f1 on Fedora 29 (kernel version 4.18.16-300) throws this warning after having set the api key in Wakatime preferences. It then fails to log my time.
```
<WakaTime> Initializing...
<WakaTime> Sending heartbeat...
<WakaTime> Network is unreachable. Consider disabling completely if you're working offline
```
Perhaps this is an issue only related to Linux, not tested on Windows or Mac.

**Comment by vladfaust** [comment]
Unity on Linux? ¯\\\_(ツ)\_/¯

**Comment by MyIsaak** [comment]
Yes, it's much better than windows obviously :smile: 
Perhaps I can come up with a patch.

**Comment by russmatney** [comment]
Not enough to close this, but just wanted to comment that it did work for me as advertised on Manjaro/Arch `running: 5.5.18-1-MANJARO (linux55)`. Thanks for the effort!

**Comment by MyIsaak** [comment]
It still
